# Generated by Django 5.1.2 on 2024-10-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("linkedin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="managers",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
